/**
 * Single frontend contract for command names registered by the Tauri backend.
 * Keeping names here prevents silent string drift between feature adapters.
 */
export const TAURI_COMMANDS = {
  initDatabase: 'init_database',
  savePageLegacy: 'save_page',
  getPagesLegacy: 'get_pages',
  deletePageLegacy: 'delete_page',
  saveAppTitle: 'save_app_title',
  getAppTitle: 'get_app_title',
  getAppDataDir: 'get_app_data_dir',
  getDataPath: 'get_data_path',
  getDataPathStatus: 'get_data_path_status',
  openDataFolder: 'open_data_folder',
  importMemojiDatabase: 'import_memoji_database',
  exportPagesZip: 'export_pages_zip',
  exportDiagnosticZip: 'export_diagnostic_zip',
  localAiStatus: 'local_ai_status',
  localAiManagedRuntimeStatus: 'local_ai_managed_runtime_status',
  localAiStartManagedRuntime: 'local_ai_start_managed_runtime',
  localAiLoad: 'local_ai_load',
  localAiGetRuntimeConfig: 'local_ai_get_runtime_config',
  localAiSaveRuntimeConfig: 'local_ai_save_runtime_config',
  localAiTestRuntimeConfig: 'local_ai_test_runtime_config',
  localAiBenchmark: 'local_ai_benchmark',
  localAiGenerate: 'local_ai_generate',
  localAiGenerateStream: 'local_ai_generate_stream',
  localAiGenerateMtpStream: 'local_ai_generate_mtp_stream',
  localAiCancel: 'local_ai_cancel',
  createAiRun: 'create_ai_run',
  finishAiRun: 'finish_ai_run',
  createAiProposal: 'create_ai_proposal',
  getAiProposal: 'get_ai_proposal',
  listAiProposals: 'list_ai_proposals',
  applyAiProposal: 'apply_ai_proposal',
  rejectAiProposal: 'reject_ai_proposal',
  listPageSummaries: 'list_page_summaries',
  listTrashedPageSummaries: 'list_trashed_page_summaries',
  getPageBody: 'get_page_body',
  savePageV2: 'save_page_v2',
  trashPage: 'trash_page',
  restorePage: 'restore_page',
  listPageRevisions: 'list_page_revisions',
  restorePageRevision: 'restore_page_revision',
  searchWorkspace: 'search_workspace',
  reindexWorkspace: 'reindex_workspace',
  getPageAnchors: 'get_page_anchors',
  getPageLinks: 'get_page_links',
  listTasks: 'list_tasks',
  updateTask: 'update_task',
  listCalendarItems: 'list_calendar_items',
  saveCalendarEvent: 'save_calendar_event',
  deleteCalendarEvent: 'delete_calendar_event',
  exportCalendarIcs: 'export_calendar_ics',
  importCalendarIcs: 'import_calendar_ics',
} as const;

export type TauriCommandName = typeof TAURI_COMMANDS[keyof typeof TAURI_COMMANDS];
